[build]
    command = "gridsome build"
    publish = "dist"

[template]
    incoming-hooks = ["UpdateArchive"]

[template.environment]
    NEWSLETTER_NAME="Name of your newsletter"
    SLOGAN="Your slogan -  added to site title"
    DESCRIPTION="HTML meta description for your site"
    LOGO="Full URL to your logo or base64 encoded data:uri"

    FRONT_HEADLINE="Headline on the front page"
    FRONT_SUBHEADLINE="Subheadline on the front page"
    FRONT_SOCIAL_PROOF="Social proof paragraph below the subscribe box"

    EMAIL_OCTOPUS_LIST_ID="ID of your list on email octopus"
    EMAIL_OCTOPUS_API_KEY="Your email octopus api key"

    THANKYOU_HEADLINE="Headline on the thank you page"
    THANKYOU_WELCOME="Welcome message on the thank you page. Can include simple HTML."

    SOCIAL_TWITTER="Full URL to your twitter profile (Can be empty)"
    SOCIAL_EMAIL="Your eMail address (Can be empty)"

    TESTIMONIALS_HEADLINE="Headline for the testimonials section of the front page (if empty, testimonials are deactivated)"
    TESTIMONIAL_1_NAME="Testimonial #1 Name"
    TESTIMONIAL_1_IMAGE="Testimonial #1 Profile image"
    TESTIMONIAL_1_POSITION="Testimonial #1  Short bio"
    TESTIMONIAL_1_QUOTE="Testimonial #1 The actual testimonial"

    TESTIMONIAL_2_NAME="Testimonial #2 Name"
    TESTIMONIAL_2_IMAGE="Testimonial #2 Profile image"
    TESTIMONIAL_2_POSITION="Testimonial #2  Short bio"
    TESTIMONIAL_2_QUOTE="Testimonial #2 The actual testimonial"

    TESTIMONIAL_3_NAME="Testimonial #3 Name"
    TESTIMONIAL_3_IMAGE="Testimonial #3 Profile image"
    TESTIMONIAL_3_POSITION="Testimonial #3  Short bio"
    TESTIMONIAL_3_QUOTE="Testimonial #3 The actual testimonial"

    TESTIMONIAL_4_NAME="Testimonial #4 Name"
    TESTIMONIAL_4_IMAGE="Testimonial #4 Profile image"
    TESTIMONIAL_4_POSITION="Testimonial #4  Short bio"
    TESTIMONIAL_4_QUOTE="Testimonial #4 The actual testimonial"